jobs:
  docs-preview-link:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: wait-for-status
      uses: autotelic/action-wait-for-status-check@v1
      with:
        intervalSeconds: 30
        owner: elastic
        ref: ${{ github.event.pull_request.head.sha }}
        statusName: buildkite/docs-build-pr
        timeoutSeconds: 900
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: steps.wait-for-status.outputs.state == 'success'
      name: Add Docs Preview link in PR Comment
      uses: thollander/actions-comment-pull-request@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: ':page_with_curl: **DOCS PREVIEW** :sparkles: https://logstash_bk_${{
          github.event.number }}.docs-preview.app.elstc.co/diff

          '
name: Docs Preview Link
on:
  repository_dispatch:
    types: trigger-ga___add-docs-preview-link.yml
