jobs:
  scan_image:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout repo content
      uses: actions/checkout@v4
    - continue-on-error: true
      name: build tar distribution
      run: ./gradlew clean assembleTarDistribution
    - continue-on-error: true
      run: mkdir scan
    - continue-on-error: true
      run: tar -zxf ../build/logstash-*.tar.gz
      working-directory: ./scan
    - continue-on-error: true
      name: scan image
      uses: anchore/scan-action@v3
      with:
        fail-build: true
        path: ./scan
        severity-cutoff: critical
name: Scan for vulnerabilities
on:
  repository_dispatch:
    types: trigger-ga___critical_vulnerability_scan.yml
