jobs:
  main:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - continue-on-error: true
      run: git config --global user.email "43502315+logstashmachine@users.noreply.github.com"
    - continue-on-error: true
      run: git config --global user.name "logstashmachine"
    - continue-on-error: true
      name: Create Release Notes Draft
      run: ./tools/release/generate_release_notes.rb ${{ github.event.inputs.branch
        }} ${{ github.event.inputs.last_release }} ${{ github.actor }} ${{ secrets.GITHUB_TOKEN
        }}
name: Release Notes Draft generator
on:
  repository_dispatch:
    types: trigger-ga___gen_release_notes.yml
permissions:
  contents: write
  issues: write
  pull-requests: write
