jobs:
  add-to-project:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: add_to_project
      uses: octokit/graphql-action@v2.x
      with:
        GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        contentid: ${{ github.event.issue.node_id }}
        headers: '{"GraphQL-Features": "projects_next_graphql"}'
        projectid: PVT_kwDOAGc3Zs0SEg
        query: "mutation add_to_project($projectid:ID!,$contentid:ID!) {\n   addProjectV2ItemById(input:{projectId:$projectid\
          \ contentId:$contentid}) {\n    clientMutationId\n  }\n }\n"
name: Add to project
on:
  repository_dispatch:
    types: trigger-ga___logstash_project_board.yml
