jobs:
  pr_commented:
    if: github.event.issue.pull_request
    name: PR comment
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: regex-match
      uses: actions-ecosystem/action-regex-match@v2
      with:
        regex: ^@logstashmachine backport (main|[x0-9\.]+)$
        text: ${{ github.event.comment.body }}
    - continue-on-error: true
      if: ${{ steps.regex-match.outputs.group1 == '' }}
      run: exit 1
    - continue-on-error: true
      id: checkUserMember
      name: Fetch logstash-core team member list
      uses: tspascoal/get-user-teams-membership@v1
      with:
        GITHUB_TOKEN: ${{ secrets.READ_ORG_SECRET_JSVD }}
        organization: elastic
        team: logstash
        username: ${{ github.actor }}
    - continue-on-error: true
      if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
      name: Is user not a core team member?
      run: exit 1
    - continue-on-error: true
      name: checkout repo content
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
    - continue-on-error: true
      run: git config --global user.email "43502315+logstashmachine@users.noreply.github.com"
    - continue-on-error: true
      run: git config --global user.name "logstashmachine"
    - continue-on-error: true
      name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - continue-on-error: true
      run: 'mkdir ~/.elastic && echo ${{ github.token }} >> ~/.elastic/github.token

        '
    - continue-on-error: true
      run: pip install requests
    - continue-on-error: true
      name: run backport
      run: python devtools/backport ${{ steps.regex-match.outputs.group1 }} ${{ github.event.issue.number
        }} --remote=origin --yes
name: Backport PR to another branch
on:
  repository_dispatch:
    types: trigger-ga___pr_backporter.yml
permissions:
  contents: write
  pull-requests: write
