jobs:
  version_bumper:
    name: Bump versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch logstash-core team member list
      uses: tspascoal/get-user-teams-membership@v1
      with:
        GITHUB_TOKEN: ${{ secrets.READ_ORG_SECRET_JSVD }}
        organization: elastic
        team: logstash
        username: ${{ github.actor }}
    - continue-on-error: true
      if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
      name: Is user a core team member?
      run: exit 1
    - continue-on-error: true
      name: checkout repo content
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch }}
    - continue-on-error: true
      run: git config --global user.email "43502315+logstashmachine@users.noreply.github.com"
    - continue-on-error: true
      run: git config --global user.name "logstashmachine"
    - continue-on-error: true
      run: ./gradlew clean installDefaultGems
    - continue-on-error: true
      run: ./vendor/jruby/bin/jruby -S bundle update --all --${{ github.event.inputs.bump
        }} --strict
    - continue-on-error: true
      run: mv Gemfile.lock Gemfile.jruby-*.lock.release
    - continue-on-error: true
      run: echo "T=$(date +%s)" >> $GITHUB_ENV
    - continue-on-error: true
      run: echo "BRANCH=update_lock_${T}" >> $GITHUB_ENV
    - continue-on-error: true
      run: 'git checkout -b $BRANCH

        git add .

        git status

        if [[ -z $(git status --porcelain) ]]; then echo "No changes. We''re done.";
        exit 0; fi

        git commit -m "Update ${{ github.event.inputs.bump }} plugin versions in gemfile
        lock" -a

        git push origin $BRANCH

        '
    - continue-on-error: true
      name: Create Pull Request
      run: 'curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d
        "{\"title\": \"bump lock file for ${{ github.event.inputs.branch }}\",\"head\":
        \"${BRANCH}\",\"base\": \"${{ github.event.inputs.branch }}\"}" https://api.github.com/repos/elastic/logstash/pulls

        '
name: Bump dependencies
on:
  repository_dispatch:
    types: trigger-ga___version_bumps.yml
permissions:
  contents: write
  pull-requests: write
